# Generated by Django 4.2.2 on 2023-06-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='a1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('treated_for', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=100)),
                ('prescription_type', models.CharField(max_length=100)),
                ('previous_history', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=10)),
                ('health_insurance', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='a2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('prescription', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=10)),
                ('health_insurance', models.CharField(max_length=10)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app47.a1')),
            ],
        ),
    ]
